class UserModel{
  final String? Id;
  final String? userName;
  final String userEmail;
  final String userPhoneNumber;
  final String userSkills;

  final String userPostOffice;
  final String userSubDistrict;
  final String userDistrict;

  UserModel({
    this.Id,
    this.userName,
    required this.userEmail,
    required this.userPhoneNumber,
    required this.userSkills,
    required this.userPostOffice,
    required this.userSubDistrict,
    required this.userDistrict});
}

class GetUserName{
  final String ?documentId;
  GetUserName({this.documentId});
}

final List<String> skills = [
  'Commitment',
  'Communication',
  'Compassion',
  'Leadership',
  'Strong work ethic',
  'Teamwork',
  'First Aid and CPR',
  'Event Planning',
  'Teaching and Tutoring',
  'Fundraising',
  'Environmental Conservation',
  'Social Media Management',
  'Graphic Design',
  'Translation and Interpretation',
  'Cooking and Food Preparation',
  'Childcare',
  'Animal Care',
  'Administrative Skills',
  'Mentoring and Counseling',
  'Construction and Maintenance',
  'Photography and Videography',
  'Legal Assistance',
  'Health and Wellness',
  'Tech Support',
  'Arts and Crafts',
  'Crisis Intervention',
  'Data Entry',
  'Database Management',
  'Disaster Response',
  'Driving',
  'Editing and Proofreading',
  'Elder Care',
  'Emergency Management',
  'Financial Management',
  'Fitness Training',
  'Grant Writing',
  'Graphic Design',
  'Gardening',
  'Home Repair',
  'Hospitality',
  'Human Resources',
  'IT Support',
  'Journalism',
  'Library Management',
  'Logistics',
  'Marketing',
  'Medical Assistance',
  'Music Instruction',
  'Nutrition',
  'Occupational Therapy',
  'Office Management',
  'Park Maintenance',
  'Patient Advocacy',
  'Peer Support',
  'Project Management',
  'Public Speaking',
  'Research',
  'Shelter Assistance',
  'Special Education',
  'Speech Therapy',
  'Sports Coaching',
  'Strategic Planning',
  'Substance Abuse Counseling',
  'Therapeutic Recreation',
  'Transportation Coordination',
  'Urban Planning',
  'Veterinary Assistance',
  'Volunteer Coordination',
  'Web Development',
  'Youth Mentoring',
  'Accounting',
  'Advocacy',
  'Animal Rescue',
  'Art Therapy',
  'Audio/Visual Setup',
  'Barber/Hairdresser',
  'Blogging',
  'Bookkeeping',
  'Budgeting',
  'Carpentry',
  'Child Development',
  'Civic Engagement',
  'Community Outreach',
  'Conflict Resolution',
  'Cooking Classes',
  'Cultural Awareness',
  'Customer Service',
  'Data Analysis',
  'Design Thinking',
  'Digital Marketing',
  'Diversity Training',
  'Drone Operation',
  'E-commerce',
  'Electrical Work',
  'Emotional Support',
  'Engineering',
  'Environmental Science',
  'Event Coordination',
  'Fashion Design',
  'Filmmaking',
  'Fitness Coaching',
  'Floral Design',
  'Food Security',
  'Forestry',
  'GIS Mapping',
  'Green Building',
  'Handyman Services',
  'Health Education',
  'Home Health Care',
  'Human Rights Advocacy',
  'Hydrology',
  'Inclusion Training',
  'Information Security',
  'Informatics',
  'Journal Writing',
  'Landscaping',
  'Language Teaching',
  'Leadership Development',
  'Legal Research',
  'Literacy Programs',
  'Lobbying',
  'Market Research',
  'Medical Research',
  'Mentoring Programs',
  'Mental Health Support',
  'Mobile App Development',
  'Nonprofit Management',
  'Nursing',
  'Operations Management',
  'Organizational Development',
  'Parenting Support',
  'Personal Training',
  'Pet Therapy',
  'Podcasting',
  'Program Evaluation',
  'Public Health',
  'Public Policy',
  'Public Relations',
  'Publishing',
  'Recycling Programs',
  'Refugee Support',
  'Renewable Energy',
  'Retail Assistance',
  'Robotics',
  'Safety Training',
  'Sanitation Services',
  'Senior Services',
  'Set Design',
  'Sexual Health Education',
  'Social Work',
  'Speech Writing',
  'STEM Education',
  'Suicide Prevention',
  'Sustainable Farming',
  'Tax Preparation',
  'Technical Writing',
  'Therapy Services',
  'Trade Skills',
  'Translation Services',
  'Travel Planning',
  'Tutoring Services',
  'UX/UI Design',
  'Video Editing',
  'Virtual Assistance',
  'Volunteer Management',
  'Water Quality Testing',
  'Wildlife Conservation',
  'Women’s Health',
  'Workforce Development',
  'Writing Workshops',
  'Adventure Training',
  'Agricultural Science',
  'Aquatic Sports Instruction',
  'Astrophotography',
  'Astronomy',
  'Auto Repair',
  'Baking',
  'Ballroom Dancing',
  'Bee Keeping',
  'Bioinformatics',
  'Biology Tutoring',
  'Blacksmithing',
  'Boat Maintenance',
  'Bodybuilding Coaching',
  'Botany',
  'Ceramic Art',
  'Choreography',
  'Circus Arts',
  'Community Gardening',
  'Composting',
  'Conservation Biology',
  'Content Creation',
  'Costume Design',
  'Craftsmanship',
  'Creative Writing',
  'Cybersecurity',
  'Dance Therapy',
  'Dental Assistance',
  'Dietetics',
  'DIY Projects',
  'Drone Photography',
  'Ecological Research',
  'Electronics Repair',
  'Environmental Activism',
  'Family Counseling',
  'Fashion Styling',
  'Film Production',
  'Fish Farming',
  'Food Distribution',
  'Genealogy',
  'Geology',
  'Habitat Restoration',
  'Hiking Guide',
  'Historical Research',
  'Homebrewing',
  'Horticulture',
  'Hypnotherapy',
  'Illustration',
  'Industrial Design',
  'Interior Design',
  'Jewelry Making',
  'Land Conservation',
  'Leather Crafting',
  'Marine Biology',
  'Martial Arts Instruction',
  'Masonry',
  'Meteorology',
  'Molecular Biology',
  'Mountaineering',
  'Music Composition',
  'Mycology',
  'Nature Photography',
  'Ornithology',
  'Parkour Instruction',
  'Personal Finance Coaching',
  'Pet Grooming',
  'Pottery',
  'Public Art Installation',
  'Quilting',
  'Raptor Rehabilitation',
  'Robotics Engineering',
  'Rock Climbing Instruction',
  'Screenwriting',
  'Sculpting',
  'Sewing',
  'Speech Pathology',
  'Stage Management',
  'Storytelling',
  'Surfing Instruction',
  'Sustainable Design',
  'Theater Direction',
  'Tour Guiding',
  'Video Game Development',
  'Watercolor Painting',
  'Wilderness Survival Training',
  'Wind Instrument Instruction',
  'Woodworking',
  'Yoga Instruction'
];

final List<String> bloodGroups = [
  'A+',
  'A-',
  'B+',
  'B-',
  'AB+',
  'AB-',
  'O+',
  'O-'
];