// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYeolQTW_tPA5FG9SLAegXdRiurOozvSc',
    appId: '1:1063292408157:web:2a39c33192ff4ed16058b4',
    messagingSenderId: '1063292408157',
    projectId: 'sahayagi-6f549',
    authDomain: 'sahayagi-6f549.firebaseapp.com',
    storageBucket: 'sahayagi-6f549.appspot.com',
    measurementId: 'G-9QF4MR6G2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF89cJO521foKAYZ_F_a9sdwoeHcE-ycg',
    appId: '1:1063292408157:android:9095287c6f2a71a76058b4',
    messagingSenderId: '1063292408157',
    projectId: 'sahayagi-6f549',
    storageBucket: 'sahayagi-6f549.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Q4TchK0gYhQyQb83rnb0Gm47dDPZl_I',
    appId: '1:1063292408157:ios:a407bd029bf167da6058b4',
    messagingSenderId: '1063292408157',
    projectId: 'sahayagi-6f549',
    storageBucket: 'sahayagi-6f549.appspot.com',
    androidClientId: '1063292408157-ced7icn4lb3ddk9jfjj66s754hfqnepr.apps.googleusercontent.com',
    iosClientId: '1063292408157-dj8t9bgekkaqei6psjik9m8bsrg16331.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahayagi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Q4TchK0gYhQyQb83rnb0Gm47dDPZl_I',
    appId: '1:1063292408157:ios:a407bd029bf167da6058b4',
    messagingSenderId: '1063292408157',
    projectId: 'sahayagi-6f549',
    storageBucket: 'sahayagi-6f549.appspot.com',
    androidClientId: '1063292408157-ced7icn4lb3ddk9jfjj66s754hfqnepr.apps.googleusercontent.com',
    iosClientId: '1063292408157-dj8t9bgekkaqei6psjik9m8bsrg16331.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahayagi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYeolQTW_tPA5FG9SLAegXdRiurOozvSc',
    appId: '1:1063292408157:web:9ad1419cbd315bdf6058b4',
    messagingSenderId: '1063292408157',
    projectId: 'sahayagi-6f549',
    authDomain: 'sahayagi-6f549.firebaseapp.com',
    storageBucket: 'sahayagi-6f549.appspot.com',
    measurementId: 'G-TKSLJLN6RS',
  );

}